/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

import tiendamiguelito.Reporte;
import java.io.FileWriter;
import java.io.IOException;
import tiendamiguelito.Producto;

/**
 *
 * @author USER
 */
public class ventReporte extends javax.swing.JFrame {
    private ventInicio padre;
    private Reporte reporteActual;
    /**
     * Creates new form Reporte1
     */
    public ventReporte() {
        initComponents();
    }
    public ventReporte(ventInicio padre, Reporte reporteActual) {
        initComponents();
        this.padre = padre;
        this.reporteActual = reporteActual;
        
        reporteActual.mostrarProductos(list_listaMostrando);
        lbl_cantTotal.setText(reporteActual.obtenerTotal()+"");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lbl_iconGuardar = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbl_iconAtras = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        lbl_cantTotal = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        list_listaMostrando = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_iconGuardar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_iconGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/iconGuardar.png"))); // NOI18N
        lbl_iconGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_iconGuardarMouseClicked(evt);
            }
        });
        jPanel2.add(lbl_iconGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 35, 35));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/CuaAzul.png"))); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, -1, -1));

        lbl_iconAtras.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_iconAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/IconVolver.png"))); // NOI18N
        lbl_iconAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_iconAtrasMouseClicked(evt);
            }
        });
        jPanel2.add(lbl_iconAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 35, 35));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/CuaBlanco.png"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("REPORTE DE VENTA");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Producto: ");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 70, 30));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel3.setAlignmentX(0.0F);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("TOTAL:");

        lbl_cantTotal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_cantTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_cantTotal.setText("00.00");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(lbl_cantTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lbl_cantTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 210, 40));

        list_listaMostrando.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        list_listaMostrando.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(list_listaMostrando);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 210, 100));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_iconAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_iconAtrasMouseClicked
        padre.setLocationRelativeTo(this);
        padre.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lbl_iconAtrasMouseClicked

    private void lbl_iconGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_iconGuardarMouseClicked
        try {
            generarReporte();
        } catch (IOException e) {
            e.printStackTrace();// Manejo básico de la excepción, puedes personalizarlo según tus necesidades.
        }
    }//GEN-LAST:event_lbl_iconGuardarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventReporte().setVisible(true);
            }
        });
    }
    
    public void generarReporte() throws IOException{
        FileWriter fichero = new FileWriter
        ("C:/Users/USER/Downloads/reporteVenta.txt");
        
        fichero.write("Producto       |    Talla     |    Precio\n");
        for (int i = 0; i < reporteActual.tamaño(); i++) {
            Producto prod = reporteActual.obtenerProducto(i);
            fichero.write(prod.getNombre() + "         |    " + prod.getTalla() 
            + "    |    " + prod.getPrecio() + "\n");
        }
        fichero.write("Total:      " + reporteActual.obtenerTotal());
        
        fichero.close();      
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_cantTotal;
    private javax.swing.JLabel lbl_iconAtras;
    private javax.swing.JLabel lbl_iconGuardar;
    private javax.swing.JList<String> list_listaMostrando;
    // End of variables declaration//GEN-END:variables
}
